name: Publish

on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn --frozen-lockfile
      - name: Publish package
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
